# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: lazyk

on:
  push:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Install uv
        run: pip install uv
      - name: Sync project dependencies
        run: uv sync
      - name: Build lazyk
        run: uv build
      - name: Install lazyk
        run: uv pip install . --verbose
      - name: Run tests
        run: uv run python -m pytest -v
